name: Build and Deploy Dev Backend

on:
  workflow_dispatch:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Change Directory
        run: cd server

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Generate deployment package
        run: zip -r deploy-dev.zip ./server/dist -x '*.git*'
